# Generated by Django 3.2.20 on 2023-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
