# Generated by Django 3.2.20 on 2023-07-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['date']},
        ),
    ]
